version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    
    volumes:
      - ./qdrant_storage:/qdrant/storage
    
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
