version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    
    # ADD THIS ENVIRONMENT SECTION
    environment:
      # The double underscores are important! They map to config settings.
      - QDRANT__SERVICE__API_KEY=${QDRANT_SECRET_API_KEY}
    
    volumes:
      - ./qdrant_storage:/qdrant/storage
    
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
