version: '3.8'

services:
  qdrant:
    # This tells Docker to use the official, pre-built image. No compiling!
    image: qdrant/qdrant:latest

    # This section is the CRITICAL part that prevents server crashes.
    deploy:
      resources:
        limits:
          cpus: '1.0'   # Limit the container to a maximum of 1 CPU core.
          memory: 2G    # Limit the container to a maximum of 2GB of RAM.
        reservations:
          cpus: '0.5'   # Ensure it has at least 0.5 CPU core available to start.
          memory: 1G    # Ensure it has at least 1GB of RAM available to start.
